# 埋め込みアプリのプロパティを定義できる構成ファイル。このファイルの場所により、CLI に対して Web コンポーネント ディレクトリが識別されます。
name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks"

[commands]
dev = "npm exec remix dev"

[hmr_server]
http_paths = ["/ping"]
