# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "member-registration"
client_id = "e8d52447bd1a3aa0bd32f4ec64c06143"
application_url = "https://brunswick-meanwhile-currencies-streaming.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://brunswick-meanwhile-currencies-streaming.trycloudflare.com/auth/callback",
  "https://brunswick-meanwhile-currencies-streaming.trycloudflare.com/auth/shopify/callback",
  "https://brunswick-meanwhile-currencies-streaming.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "krb-kuro.myshopify.com"
