#プロジェクトのメタデータと構成を含むファイル。このファイルはアプリのルートを表します。
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

application_url = "https://pencil-meta-hit-oliver.trycloudflare.com"
client_id = "e8d52447bd1a3aa0bd32f4ec64c06143"
embedded = true
name = "member-registration"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pencil-meta-hit-oliver.trycloudflare.com/auth/callback",
  "https://pencil-meta-hit-oliver.trycloudflare.com/auth/shopify/callback",
  "https://pencil-meta-hit-oliver.trycloudflare.com/api/auth/callback",
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "krb-kuro.myshopify.com"
